#!/usr/bin/expect
set timeout 10
spawn ssh -o StrictHostKeyChecking=no root@5.144.181.38
expect "root@5.144.181.38's password:"
send "7TdYGUmsPt3ao1\r"
expect "root@hiplet-41895:~#"
send "cd /opt/birdwatching\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА СТАТУСА КОНТЕЙНЕРОВ ==='\r"
expect "=== ПРОВЕРКА СТАТУСА КОНТЕЙНЕРОВ ==="
send "docker ps\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ПОРТОВ ==='\r"
expect "=== ПРОВЕРКА ПОРТОВ ==="
send "netstat -tlnp | grep -E ':(3010|3011|8080)'\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ЛОГОВ ФРОНТЕНДА ==='\r"
expect "=== ПРОВЕРКА ЛОГОВ ФРОНТЕНДА ==="
send "docker logs birdwatching-frontend-1 --tail=10\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ЛОГОВ БЭКЕНДА ==='\r"
expect "=== ПРОВЕРКА ЛОГОВ БЭКЕНДА ==="
send "docker logs birdwatching-backend-1 --tail=10\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА NGINX КОНФИГУРАЦИИ ==='\r"
expect "=== ПРОВЕРКА NGINX КОНФИГУРАЦИИ ==="
send "grep -A 5 -B 5 'proxy_pass.*8080' /etc/nginx/sites-available/excursionapp\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ТЕСТИРОВАНИЕ ЛОКАЛЬНОГО ПОДКЛЮЧЕНИЯ ==='\r"
expect "=== ТЕСТИРОВАНИЕ ЛОКАЛЬНОГО ПОДКЛЮЧЕНИЯ ==="
send "curl -I http://localhost:8080\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "curl -I http://localhost:3010\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ЗАВЕРШЕНА ==='\r"
expect "=== ПРОВЕРКА ЗАВЕРШЕНА ==="
send "exit\r"
interact
