#!/usr/bin/expect
set timeout 10
spawn ssh -o StrictHostKeyChecking=no root@5.144.181.38
expect "root@5.144.181.38's password:"
send "7TdYGUmsPt3ao1\r"
expect "root@hiplet-41895:~#"
send "cd /opt/birdwatching\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА КОНФИГУРАЦИИ NGINX ==='\r"
expect "=== ПРОВЕРКА КОНФИГУРАЦИИ NGINX ==="
send "cat /etc/nginx/sites-available/excursionapp | grep -A 10 -B 5 'location /'\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА СИМВОЛИЧЕСКИХ ССЫЛОК ==='\r"
expect "=== ПРОВЕРКА СИМВОЛИЧЕСКИХ ССЫЛОК ==="
send "ls -la /etc/nginx/sites-enabled/\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА АКТИВНОЙ КОНФИГУРАЦИИ ==='\r"
expect "=== ПРОВЕРКА АКТИВНОЙ КОНФИГУРАЦИИ ==="
send "nginx -T | grep -A 10 -B 5 'location /'\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ПРОЦЕССОВ NGINX ==='\r"
expect "=== ПРОВЕРКА ПРОЦЕССОВ NGINX ==="
send "ps aux | grep nginx\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПЕРЕЗАПУСК NGINX ==='\r"
expect "=== ПЕРЕЗАПУСК NGINX ==="
send "systemctl restart nginx\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ТЕСТИРОВАНИЕ ПОСЛЕ ПЕРЕЗАПУСКА ==='\r"
expect "=== ТЕСТИРОВАНИЕ ПОСЛЕ ПЕРЕЗАПУСКА ==="
send "curl -I https://excursionapp.mywire.org\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ЗАВЕРШЕНА ==='\r"
expect "=== ПРОВЕРКА ЗАВЕРШЕНА ==="
send "exit\r"
interact