#!/usr/bin/expect
set timeout 10
spawn ssh -o StrictHostKeyChecking=no root@5.144.181.38
expect "root@5.144.181.38's password:"
send "7TdYGUmsPt3ao1\r"
expect "root@hiplet-41895:~#"
send "cd /opt/birdwatching\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ПОРТА 8080 ==='\r"
expect "=== ПРОВЕРКА ПОРТА 8080 ==="
send "ss -tlnp | grep :8080\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА DOCKER ПОРТОВ ==='\r"
expect "=== ПРОВЕРКА DOCKER ПОРТОВ ==="
send "docker port birdwatching-frontend-1\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ТЕСТИРОВАНИЕ ЛОКАЛЬНОГО ПОДКЛЮЧЕНИЯ ==='\r"
expect "=== ТЕСТИРОВАНИЕ ЛОКАЛЬНОГО ПОДКЛЮЧЕНИЯ ==="
send "curl -I http://localhost:8080\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "curl -I http://127.0.0.1:8080\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ЛОГОВ NGINX ==='\r"
expect "=== ПРОВЕРКА ЛОГОВ NGINX ==="
send "tail -10 /var/log/nginx/error.log\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ЗАВЕРШЕНА ==='\r"
expect "=== ПРОВЕРКА ЗАВЕРШЕНА ==="
send "exit\r"
interact
