#!/usr/bin/expect
set timeout 10
spawn ssh -o StrictHostKeyChecking=no root@5.144.181.38
expect "root@5.144.181.38's password:"
send "7TdYGUmsPt3ao1\r"
expect "root@hiplet-41895:~#"
send "cd /opt/birdwatching\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ИСПРАВЛЕНИЕ NGINX НА ПРАВИЛЬНЫЙ ПОРТ ==='\r"
expect "=== ИСПРАВЛЕНИЕ NGINX НА ПРАВИЛЬНЫЙ ПОРТ ==="
send "sed -i 's/proxy_pass http:\\/\\/127\\.0\\.0\\.1:3011/proxy_pass http:\\/\\/127\\.0\\.0\\.1:8080/g' /etc/nginx/sites-available/excursionapp\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ИЗМЕНЕНИЙ ==='\r"
expect "=== ПРОВЕРКА ИЗМЕНЕНИЙ ==="
send "grep -A 5 -B 5 'proxy_pass.*8080' /etc/nginx/sites-available/excursionapp\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПЕРЕЗАГРУЗКА NGINX ==='\r"
expect "=== ПЕРЕЗАГРУЗКА NGINX ==="
send "nginx -t\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "systemctl reload nginx\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ТЕСТИРОВАНИЕ ==='\r"
expect "=== ТЕСТИРОВАНИЕ ==="
send "curl -I https://excursionapp.mywire.org\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "curl -X POST https://excursionapp.mywire.org/auth/login -H 'Content-Type: application/json' -d '{\"email\":\"test@test.com\",\"password\":\"test\"}' -v\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ИСПРАВЛЕНИЕ ЗАВЕРШЕНО ==='\r"
expect "=== ИСПРАВЛЕНИЕ ЗАВЕРШЕНО ==="
send "exit\r"
interact
