#!/usr/bin/expect
set timeout 10
spawn ssh -o StrictHostKeyChecking=no root@5.144.181.38
expect "root@5.144.181.38's password:"
send "7TdYGUmsPt3ao1\r"
expect "root@hiplet-41895:~#"
send "cd /opt/birdwatching\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПОЛНОЕ ИСПРАВЛЕНИЕ NGINX ==='\r"
expect "=== ПОЛНОЕ ИСПРАВЛЕНИЕ NGINX ==="
send "sed -i 's/127\\.0\\.0\\.1:3011/127.0.0.1:8080/g' /etc/nginx/sites-available/excursionapp\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ВСЕХ ВХОЖДЕНИЙ ==='\r"
expect "=== ПРОВЕРКА ВСЕХ ВХОЖДЕНИЙ ==="
send "grep -n 'proxy_pass' /etc/nginx/sites-available/excursionapp\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА СИНТАКСИСА ==='\r"
expect "=== ПРОВЕРКА СИНТАКСИСА ==="
send "nginx -t\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПЕРЕЗАГРУЗКА NGINX ==='\r"
expect "=== ПЕРЕЗАГРУЗКА NGINX ==="
send "systemctl reload nginx\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ТЕСТИРОВАНИЕ ==='\r"
expect "=== ТЕСТИРОВАНИЕ ==="
send "curl -I https://excursionapp.mywire.org\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ПРОВЕРКА ЛОГОВ NGINX ==='\r"
expect "=== ПРОВЕРКА ЛОГОВ NGINX ==="
send "tail -5 /var/log/nginx/error.log\r"
expect "root@hiplet-41895:/opt/birdwatching#"
send "echo '=== ИСПРАВЛЕНИЕ ЗАВЕРШЕНО ==='\r"
expect "=== ИСПРАВЛЕНИЕ ЗАВЕРШЕНО ==="
send "exit\r"
interact